export const DEFAULT_REGIONAL_EXTENT = false;
export const DEFAULT_SHOW_ZOOM_BUTTON = true;
export const DEFAULT_SHOW_RESET_BUTTON = true;
export const DEFAULT_SHOW_FULLSCREEN_BUTTON = false;
export const DEFAULT_SHOW_GLOBE_OVERVIEW = false;
export const DEFAULT_SHOW_ASSET_POPUP = false;
export const DEFAULT_SHOW_GRATICULE = false;
export const DEFAULT_CENTER: [number, number] = [-180, -90];
export const DEFAULT_THEME = 'bsk-2';
