// This file is auto-generated. Do not edit manually.
// Run 'npm run extract-theme-variables' to regenerate.

export const generatedThemeConfig = {
  extend: {
    theme: {
      font: ['sans'],
      colors: [
        'accent-1',
        'accent-10',
        'accent-11',
        'accent-12',
        'accent-2',
        'accent-3',
        'accent-4',
        'accent-5',
        'accent-6',
        'accent-7',
        'accent-8',
        'accent-9',
        'accent-a1',
        'accent-a10',
        'accent-a11',
        'accent-a12',
        'accent-a2',
        'accent-a3',
        'accent-a4',
        'accent-a5',
        'accent-a6',
        'accent-a7',
        'accent-a8',
        'accent-a9',
        'accent-contrast',
        'accent-indicator',
        'accent-surface',
        'accent-track',
        'black',
        'border',
        'bright-blue',
        'dark-blue',
        'dark-gray',
        'fg',
        'gray-1',
        'gray-10',
        'gray-11',
        'gray-12',
        'gray-2',
        'gray-3',
        'gray-4',
        'gray-5',
        'gray-6',
        'gray-7',
        'gray-8',
        'gray-9',
        'gray-a1',
        'gray-a10',
        'gray-a11',
        'gray-a12',
        'gray-a2',
        'gray-a3',
        'gray-a4',
        'gray-a5',
        'gray-a6',
        'gray-a7',
        'gray-a8',
        'gray-a9',
        'gray-contrast',
        'gray-indicator',
        'gray-surface',
        'gray-track',
        'htmlBackground',
        'light-blue',
        'muted',
        'seasalt',
        'white',
      ],
      shadow: ['lg', 'md', 'sm', 'xl'],
      breakpoint: ['xs'],
    },
  },
} as const;
